# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='project_images'),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
