# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaMap', '0002_remove_worldmap_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldmap',
            name='content',
            field=models.TextField(default='None'),
        ),
    ]
